### ISSUE TITLE
resnet50 init checkpoint

### ISSUE THREAD

**Issue by bknyaz** [HarborYuan/GradCosine#2]
Hi, thanks for great work. Is it possible to share the initialization of Resnet50 using your method for ImageNet? I have my codebase where I would like to load your initialization checkpoint and run training on ImageNet. It would be cool if I could compare my initialization to your method and I don't have much time to setup your codebase. 

Or maybe you can share a single python script to initialize a network with no dependencies? 

Thanks.

**Comment by HarborYuan** [comment]
Hi @bknyaz ,

Thanks for your interest.

I have updated the checkpoint after initialization, but you may need to adapt it to your codebase.

Feel free to re-open the issue and let me know if you have any other question.

Best,
Haobo Yuan

**Comment by bknyaz** [comment]
Thanks, I was able to load all params from your checkpoint to my code!

**Comment by bknyaz** [comment]
Can you also share an ImageNet checkpoint for Swin-T by any chance? :)

**Comment by bknyaz** [comment]
by the way, it seems I cannot re-open the issue for some reason

**Comment by HarborYuan** [comment]
Hi @bknyaz ,

Sorry for the delay. I have added the swin-T checkpoint to the repo.

Thanks for your interest.
